const ASSETS = [
  { id: 'sp500', symbol: '^GSPC', name: '미국 S&P 500', currency: 'USD', scale: 1 },
  { id: 'tiger-sp', symbol: '360750.KS', name: 'TIGER 미국S&P500', currency: 'KRW', scale: 1 },
  { id: 'usdkrw', symbol: 'USDKRW=X', name: '원/달러 환율', currency: 'KRW', scale: 1 },
  { id: 'tiger-nasdaq-bond', symbol: '435420.KS', name: 'TIGER 미국나스닥100채권혼합Fn', currency: 'KRW', scale: 1 },
];
let market = {};
const won = new Intl.NumberFormat('ko-KR', { maximumFractionDigits: 0 });
const usd = new Intl.NumberFormat('en-US', { maximumFractionDigits: 2 });
const fmt = (value, currency) => value == null ? '—' : currency === 'USD' ? `$${usd.format(value)}` : `${won.format(value)}원`;
const pct = value => `${value >= 0 ? '+' : ''}${value.toFixed(2)}%`;
const average = list => list.reduce((a,b) => a + b, 0) / list.length;
const stdev = list => { const m = average(list); return Math.sqrt(average(list.map(x => (x-m)**2))); };
const saved = () => JSON.parse(localStorage.getItem('marketCompassHoldings') || '[{"asset":"tiger-sp","quantity":"","cost":""},{"asset":"tiger-nasdaq-bond","quantity":"","cost":""}]');
function save() { const data = [...document.querySelectorAll('#holdings tr')].map(r => ({ asset:r.querySelector('.asset').value, quantity:r.querySelector('.quantity').value, cost:r.querySelector('.cost').value })); localStorage.setItem('marketCompassHoldings', JSON.stringify(data)); updatePortfolio(); }
function addHolding(data={asset:'tiger-sp',quantity:'',cost:''}) { const row = document.querySelector('#holding-row').content.cloneNode(true); const asset = row.querySelector('.asset'); ASSETS.filter(a=>a.id !== 'sp500' && a.id !== 'usdkrw').forEach(a => asset.add(new Option(a.name,a.id))); asset.value=data.asset; row.querySelector('.quantity').value=data.quantity; row.querySelector('.cost').value=data.cost; row.querySelectorAll('input,select').forEach(e=>e.addEventListener('input',save)); row.querySelector('.delete').addEventListener('click',e=>{e.currentTarget.closest('tr').remove();save()}); document.querySelector('#holdings').append(row); }
function sparkline(prices) { const sample=prices.slice(-60), min=Math.min(...sample), max=Math.max(...sample), range=max-min||1; const points=sample.map((p,i)=>`${i/(sample.length-1)*100},${64-(p-min)/range*58}`).join(' '); return `<svg class="spark" viewBox="0 0 100 66" preserveAspectRatio="none"><polyline fill="none" stroke="#16764b" stroke-width="2" points="${points}"/></svg>`; }
function analyze(asset, prices) { const latest=prices.at(-1), r20=(latest/prices.at(-21)-1)*100, sma20=average(prices.slice(-20)), sma60=average(prices.slice(-60)); const returns=prices.slice(-61).map((p,i)=>i?Math.log(p/prices[prices.length-62+i]):null).filter(Boolean); const vol=stdev(returns)*Math.sqrt(252)*100; const trend = latest>sma20&&sma20>sma60?'상승 추세':latest<sma20&&sma20<sma60?'하락 추세':'혼조'; const direction=trend==='상승 추세'?'up':trend==='하락 추세'?'down':'neutral'; const monthlyMean=average(returns)*21*100, monthlyRisk=stdev(returns)*Math.sqrt(21)*100; return {asset,prices,latest,r20,sma20,sma60,vol,trend,direction,monthlyMean,monthlyRisk}; }
async function getMarket(asset, snapshot) { const closes=snapshot?.assets?.[asset.id]?.closes; if(!closes || closes.length<70) throw Error('insufficient data'); return analyze(asset,closes); }
function renderMarkets() { const root=document.querySelector('#markets'); root.innerHTML=ASSETS.map(a=>{const m=market[a.id]; if(!m)return `<article class="market-card"><b>${a.name}</b><p class="down">데이터를 가져오지 못했습니다.</p></article>`;return `<article class="market-card"><div class="asset-name">${a.name}</div><div class="price">${fmt(m.latest,a.currency)}</div><b class="${m.r20>=0?'up':'down'}">최근 20거래일 ${pct(m.r20)}</b>${sparkline(m.prices)}<div class="metrics"><div><span>추세</span><b class="${m.direction}">${m.trend}</b></div><div><span>20일 평균</span><b>${fmt(m.sma20,a.currency)}</b></div><div><span>연환산 변동성</span><b>${m.vol.toFixed(1)}%</b></div></div></article>`}).join(''); }
function renderOutlooks() { const root=document.querySelector('#outlooks'); root.innerHTML=ASSETS.map(a=>{const m=market[a.id];if(!m)return ''; const low=m.monthlyMean-m.monthlyRisk, high=m.monthlyMean+m.monthlyRisk; const label=m.monthlyMean>.5?'완만한 우세':m.monthlyMean<-.5?'보수적 접근':'방향성 탐색';return `<article class="outlook"><h3>${a.name}</h3><b class="${m.monthlyMean>=0?'up':'down'}">${label}</b><p>최근 60일 특성으로 본 1개월 중심 변화율: ${pct(m.monthlyMean)}</p><p>통계적 변동 범위: ${pct(low)} ~ ${pct(high)}</p><p>근거: ${m.trend}, 최근 20일 ${pct(m.r20)}, 연환산 변동성 ${m.vol.toFixed(1)}%</p></article>`}).join(''); }
function updatePortfolio(){let value=0,costTotal=0;document.querySelectorAll('#holdings tr').forEach(row=>{const a=ASSETS.find(x=>x.id===row.querySelector('.asset').value),q=Number(row.querySelector('.quantity').value),c=Number(row.querySelector('.cost').value), price=market[a.id]?.latest; const current=q*price, invested=q*c; value+=Number.isFinite(current)?current:0;costTotal+=invested; row.querySelector('.latest').textContent=fmt(price,a.currency); const p=current-invested;row.querySelector('.pnl').innerHTML=Number.isFinite(p)&&q?`<b class="${p>=0?'up':'down'}">${fmt(p,a.currency)}<br>${pct((price/c-1)*100)}</b>`:'—';});const p=value-costTotal;document.querySelector('#total-value').textContent=value?`${won.format(value)}원`:'—';document.querySelector('#total-pnl').innerHTML=value?`<span class="${p>=0?'up':'down'}">${won.format(p)}원</span>`:'—';document.querySelector('#total-return').textContent=value&&costTotal?`수익률 ${pct((value/costTotal-1)*100)}`:'보유 수량과 매수가를 입력하세요';const trends=Object.values(market);if(trends.length){const up=trends.filter(x=>x.trend==='상승 추세').length;document.querySelector('#market-regime').textContent=up>=3?'위험선호':up<=1?'방어 우세':'혼조';document.querySelector('#market-detail').textContent=`관찰 자산 ${up}/4개 상승 추세`;}}
async function load(){document.querySelector('#data-status').textContent='저장된 종가 데이터를 불러오는 중…';try{const response=await fetch(`https://raw.githubusercontent.com/root-riverside/test/main/data/market.json?updated=${Date.now()}`);if(!response.ok)throw Error(response.status);const snapshot=await response.json();const results=await Promise.allSettled(ASSETS.map(a=>getMarket(a,snapshot)));market={};results.forEach((r,i)=>{if(r.status==='fulfilled')market[ASSETS[i].id]=r.value});renderMarkets();renderOutlooks();updatePortfolio();const updated=new Date(snapshot.updatedAt);document.querySelector('#data-status').textContent=Object.keys(market).length===4?`최근 확정 종가 반영 · 갱신 ${updated.toLocaleString('ko-KR')}`:'일부 종가가 없습니다. GitHub Actions 실행 상태를 확인하세요.';}catch(error){market={};renderMarkets();renderOutlooks();updatePortfolio();document.querySelector('#data-status').textContent='종가 파일을 찾지 못했습니다. GitHub Actions를 한 번 실행하세요.';}}
saved().forEach(addHolding);document.querySelector('#add-holding').addEventListener('click',()=>addHolding());document.querySelector('#refresh').addEventListener('click',load);load();
